version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_fishstore
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fishstore
      MYSQL_USER: fishuser
      MYSQL_PASSWORD: fishpass
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
#      - ./src/main/resources/sql/fishStructure.sql:/docker-entrypoint-initdb.d/fishStructure.sql

volumes:
  mysql_data:
